maintest: main.c
	gcc main.c tokenizer.c infix2postfix.c codegenerator.c virtualmachine.c -o maintest -lm
tokenizer: tokenizer.c
	gcc tokenizer.c
infix2postfix: infix2postfix.c
	gcc infix2postfix.c
codegenerator: codegenerator.c
	gcc codegenerator.c
virtualmachine: virtualmachine.c
	gcc virtualmachine.c -lm
